function Hd = fir_design
%FIR_DESIGN Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the DSP System Toolbox 9.3.
% Generated on: 04-Jan-2020 17:21:44

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 384000;  % Sampling Frequency

Fpass = 10000;            % Passband Frequency
Fstop = 38400;            % Stopband Frequency
Dpass = 0.17099735734;    % Passband Ripple
Dstop = 0.0056234132519;  % Stopband Attenuation
dens  = 20;               % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
